### ISSUE TITLE
Could not pass event PaperInventoryMoveItemEvent to ChestPreview v1.0.6-r2

### ISSUE THREAD

**Issue by jhqwqmc** [PluginBugs/Issues-ChestPreview#18]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

jhqwqmc#8740

### What happened?

An error will be reported when using hoppers to transfer items

### Steps to reproduce the issue

1.Put a hopper on top of the chest
2.look at the chest

### Server version

git-Purpur-2095 (MC: 1.20.2)*

### ChestPreview Version

ChestPreview version 1.0.6-r2

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ChestPreview/files/13969544/latest.log)

### Error (optional)

```shell
[06:43:29] [Server thread/ERROR]: Could not pass event PaperInventoryMoveItemEvent to ChestPreview v1.0.6-r2
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getLocation()" because "<parameter3>.a" is null
	at chestpreview.m.e.a(SourceFile:315) ~[ChestPreview_1.0.6-r2.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at java.util.Collections$SynchronizedMap.forEach(Collections.java:2735) ~[?:?]
	at chestpreview.m.e.a(SourceFile:314) ~[ChestPreview_1.0.6-r2.jar:?]
	at chestpreview.m.e.a(SourceFile:414) ~[ChestPreview_1.0.6-r2.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:git-Purpur-2095]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.callPushMoveEvent(HopperBlockEntity.java:358) ~[?:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.hopperPush(HopperBlockEntity.java:283) ~[?:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.ejectItems(HopperBlockEntity.java:469) ~[?:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.tryMoveItems(HopperBlockEntity.java:227) ~[?:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.pushItemsTick(HopperBlockEntity.java:169) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1185) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1137) ~[?:?]
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1338) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:944) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1577) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Problematic items yml configuration file (optional)

```shell
graphics:
  trigger_distance_blocks: 4
  show_title: true
  brightness:
    block_light: 15
    sky_light: 15
  position:
    distance_y: 0.2
    distance_front: -1.0
  show_on_poses:
    standing: false
    sneaking: true
    crawling: false
    swimming: false
optimization:
  container_detection_interval_ticks: 1
  optimization:
    check_container_access_permission: false
  check_container_access_permission: true
containers:
  ender_chest: true
  jukebox: true
worlds:
- '*'
```

**Comment by LoneDev6** [comment]
Can't reproduce the issue, but I will add an extra check for this

**Comment by jhqwqmc** [comment]
https://github.com/PluginBugs/Issues-ChestPreview/assets/113768629/4d97a042-dcff-4014-823f-dfbdfc28b24a

**Comment by jhqwqmc** [comment]
@LoneDev6 as shown in the video
