### ISSUE TITLE
IllegalArgumentException: Cannot measure distance between world_nether and world

### ISSUE THREAD

**Issue by Askarionn** [PluginBugs/Issues-ChestPreview#25]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

https://pastebin.com/2uRSpf7S

### Steps to reproduce the issue

worlds:
- world
- world_the_end
- world_nether

### Server version

Pufferfish version git-Pufferfish-42 (MC: 1.20.4)

### ChestPreview Version

ChestPreview version 1.0.7

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### Error (optional)

```shell
[18:32:47 WARN]: [ChestPreview] Task #3288275 for ChestPreview v1.0.7 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world_nether and world
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.Location.distance(Location.java:493) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at chestpreview.m.e.a(SourceFile:140) ~[ChestPreview_1.0.7 (1).jar:?]
        at chestpreview.m.h.b(SourceFile:430) ~[ChestPreview_1.0.7 (1).jar:?]
        at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at java.util.Collections$SynchronizedMap.forEach(Collections.java:2955) ~[?:?]
        at chestpreview.m.h.b(SourceFile:429) ~[ChestPreview_1.0.7 (1).jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.4.jar:git-Pufferfish-42]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[pufferfish-1.20.4.jar:git-Pufferfish-42]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1641) ~[pufferfish-1.20.4.jar:git-Pufferfish-42]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.20.4.jar:git-Pufferfish-42]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1520) ~[pufferfish-1.20.4.jar:git-Pufferfish-42]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[pufferfish-1.20.4.jar:git-Pufferfish-42]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[pufferfish-1.20.4.jar:git-Pufferfish-42]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by ShockCharge** [comment]
This same error is happening in my server, and it keeps spamming my console.
Take your time to fix this, LoneDev. Thank you in advance!

**Comment by LoneDev6** [comment]
Will be fixed today, thanks a lot
