### ISSUE TITLE
ChestPreview is not working

### ISSUE THREAD

**Issue by bbangjun0124** [PluginBugs/Issues-ChestPreview#35]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I put the ProtocolLib and LoneLib required for ChestPreview together in the plugin folder, but it stuck with the error below

### Steps to reproduce the issue

I put the ProtocolLib and LoneLib required for ChestPreview together in the plugin folder, but it stuck with the error below

### Server version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version

### ChestPreview Version

ChestPreview v1.0.8

### ProtocolLib Version

ProtocolLib 5.2.0

### LoneLibs Version

LoneLibs version 1.0.45

### FULL server log

[2024-05-18-1.log.gz](https://github.com/PluginBugs/Issues-ChestPreview/files/15360081/2024-05-18-1.log.gz)

### Error (optional)

```shell
[14:34:56] [Server thread/ERROR]: Error occurred while enabling ChestPreview v1.0.8 (Is it up to date?)
java.lang.RuntimeException: java.nio.file.NoSuchFileException: C:\Users\Lee%20sangjun\Desktop\server\plugins\ChestPreview_1.0.8.jar
	at chestpreview.m.d.a(SourceFile:69) ~[ChestPreview_1.0.8.jar:?]
	at chestpreview.m.e.a(SourceFile:52) ~[ChestPreview_1.0.8.jar:?]
	at dev.lone.chestpreview.Main.onEnable(SourceFile:43) ~[ChestPreview_1.0.8.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.nio.file.NoSuchFileException: C:\Users\Lee%20sangjun\Desktop\server\plugins\ChestPreview_1.0.8.jar
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1851) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1269) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:347) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:318) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:284) ~[?:?]
	at chestpreview.m.d.a(SourceFile:47) ~[ChestPreview_1.0.8.jar:?]
	... 14 more
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://forum.devs.beer/d/2461-chestpreview-is-not-working

**Comment by LoneDev6** [comment]
Remove the space character from your directory name `C:\Users\Lee sangjun`
