### ISSUE TITLE
1.21.1 support

### ISSUE THREAD

**Issue by bobhenl** [PluginBugs/Issues-ChestPreview#37]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Renzotom

### What happened?

```
[16:45:38] [Server thread/ERROR]: Error occurred while enabling ChestPreview v1.0.8-release-3 (Is it up to date?)
java.lang.RuntimeException: This server is not compatible with this plugin.
	at ChestPreview_1.0.8-release-3.jar/chestpreview.m.k.a(SourceFile:48) ~[ChestPreview_1.0.8-release-3.jar:?]
	at ChestPreview_1.0.8-release-3.jar/chestpreview.m.t.<init>(SourceFile:49) ~[ChestPreview_1.0.8-release-3.jar:?]
	at ChestPreview_1.0.8-release-3.jar/chestpreview.m.t.u(SourceFile:66) ~[ChestPreview_1.0.8-release-3.jar:?]
	at ChestPreview_1.0.8-release-3.jar/dev.lone.chestpreview.Main.onEnable(SourceFile:74) ~[ChestPreview_1.0.8-release-3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:756) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:518) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Steps to reproduce the issue

Try 1.21 server version

### Server version

[16:44:20] [ServerMain/INFO]: [bootstrap] Running Java 21 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS; Eclipse Adoptium Temurin-21.0.3+9) on Linux 6.1.0-21-amd64 (amd64)
[16:44:20] [ServerMain/INFO]: [bootstrap] Loading Purpur 1.21-2274-ver/1.21@c3849be (2024-07-23T02:04:15Z) for Minecraft 1.21

### ChestPreview Version

 v1.0.8-release-3

### ProtocolLib Version

v5.3.0-SNAPSHOT-726

### LoneLibs Version

 v1.0.56

**Comment by TylorTurner** [comment]
Any chance on a 1.21 version of ChestPreview soon?

**Comment by bobhenl** [comment]
I don't think so

**Comment by DxrkCxt** [comment]
LoneDev when is 1.21 and 1.21.1 support? Can you add please really need this update.

**Comment by TylorTurner** [comment]
Please
