### ISSUE TITLE
ChestPreview doesn't work on 1.21.4

### ISSUE THREAD

**Issue by Liedocoin** [PluginBugs/Issues-ChestPreview#42]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

-

### What happened?

Hello!
I'm installed ChestPreview 1.0.9 plugin on Purpur 1.21.4 server, LoneLibs 1.0.63, ProtocolLib 5.4.0-SNAPSHOT-738.

The plugin failed to start, giving the following error: https://pastebin.com/8nVjzRgS

If you can - update the plugin quickly, thank you

### Steps to reproduce the issue

-

### Server version

(Current Purpur Version: 1.21.4-2376-4bf1b98 (MC: 1.21.4)*
You are running the latest version)

### ChestPreview Version

ChestPreview 1.0.9

### ProtocolLib Version

ProtocolLib 5.4.0-SNAPSHOT-738.

### LoneLibs Version

LoneLibs 1.0.63

### FULL server log

-

### Error (optional)

```shell
Error occurred while enabling ChestPreview v1.0.9 (Is it up to date?)
java.lang.RuntimeException: This server is not compatible with this plugin.
        at ChestPreview_1.0.9.jar/chestpreview.m.k.a(SourceFile:48) ~[ChestPreview_1.0.9.jar:?]
        at ChestPreview_1.0.9.jar/chestpreview.m.t.<init>(SourceFile:49) ~[ChestPreview_1.0.9.jar:?]
        at ChestPreview_1.0.9.jar/chestpreview.m.t.u(SourceFile:66) ~[ChestPreview_1.0.9.jar:?]
        at ChestPreview_1.0.9.jar/dev.lone.chestpreview.Main.onEnable(SourceFile:74) ~[ChestPreview_1.0.9.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[purpur-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:669) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:618) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:772) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:534) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:369) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:344) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:07:52 INFO]: [ChestPreview] Disabling ChestPreview v1.0.9
```

### Problematic items yml configuration file (optional)

```shell
-
```

### Other files, you can drag and drop them here to upload. (optional)

-

### Screenshots/Videos (you can drag and drop files or paste links)

-

**Comment by DxrkCxt** [comment]
Please add support for 1.21.4

**Comment by DxrkCxt** [comment]
You literally just need to duplicate the class for 1.21.1 and write VERSION_1_21_4 there and that's it, can you please do.

**Comment by BronzWarq** [comment]
Please add support for 1.21.4 =\
