### ISSUE TITLE
Conflict with EcoShop

### ISSUE THREAD

**Issue by DxrkCxt** [PluginBugs/Issues-ChestPreview#7]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

```
user issued server command: /shop
[23:30:38 WARN]: [ChestPreview] Task #44736 for ChestPreview v1.0.4 generated an exception
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "<parameter1>" is null
	at chestpreview.m.b.b(SourceFile:224) ~[chestpreview-1.0.4.jar:?]
	at chestpreview.m.d.a(SourceFile:291) ~[chestpreview-1.0.4.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
	at java.util.Collections$SynchronizedMap.forEach(Collections.java:2955) ~[?:?]
	at chestpreview.m.d.b(SourceFile:290) ~[chestpreview-1.0.4.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[linearpurpur-1.20.2.jar:git-LinearPurpur-"bacf5f3"]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[linearpurpur-1.20.2.jar:git-LinearPurpur-"bacf5f3"]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1497) ~[linearpurpur-1.20.2.jar:git-LinearPurpur-"bacf5f3"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[linearpurpur-1.20.2.jar:git-LinearPurpur-"bacf5f3"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[linearpurpur-1.20.2.jar:git-LinearPurpur-"bacf5f3"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[linearpurpur-1.20.2.jar:git-LinearPurpur-"bacf5f3"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[linearpurpur-1.20.2.jar:git-LinearPurpur-"bacf5f3"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Steps to reproduce the issue

Simply run  /shop command from the EcoShop plugin

### ChestPreview Version

1.0.4

### ProtocolLib Version

ver ProtocolLib
[23:51:48 INFO]: ProtocolLib version 5.1.1-SNAPSHOT-673
[23:51:48 INFO]: Provides read/write access to the Minecraft protocol.
[23:51:48 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

ver LoneLibs
[23:51:54 INFO]: LoneLibs version 1.0.31
[23:51:54 INFO]: Collection of libs used by my plugins
[23:51:54 INFO]: Authors: LoneDev and others

**Comment by LoneDev6** [comment]
Will be fixed with #3
